name: dart_mailer
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  mysql1: ^0.19.2
  mysql_client: ^0.0.19
  uuid: ^3.0.6
  encrypt: ^5.0.1
  mailer: ^5.1.1
  http: ^0.13.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.15.0
